apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: dev
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: "0.5"
          memory: 512Mi
        requests:
          cpu: "0.1"
          memory: 256Mi
